---
title: "CP_staggered-level_BayesianD_functions"
output: html_document
---
```{r}
Dcriterion_staggered <- function(mSSD, U2, f = f, b1 = b1, n1 = n1, n2 = n2){
  index.matrix <- combn(ncol(mSSD), f)
  library(Matrix)   
  U1 <- kronecker(diag(b1),matrix(1,n2,1))
  S <- diag(b1 * n2) + (1 * U1 %*% t(U1)) + (1 * U2 %*% t(U2)) # 1 is from paper
  
  Df <- 0
  for(i in 1:ncol(index.matrix)){
    Xf <- cbind(1, mSSD[ ,index.matrix[,i]])
    #Df <- Df + det(t(Xf) %*% solve(S) %*% Xf)^(1/(f+1))
    Df <- Df + round(det(t(Xf) %*% solve(S) %*% Xf),6)^(1/(f+1))
  }
  return(Df / choose(ncol(mSSD), f))
}
```

```{r}
evaluateMBayesianD <- function(MSSD, U2, b1 ,n2){
  tau <- sqrt(5)
  m <- ncol(MSSD)
  
  #primary
  primary <- matrix(1,nrow = nrow(MSSD),1)
  p1 <- ncol(primary)
  
  #potential
  potential <- MSSD
  p2 <- ncol(potential)
  potential.adj <- potential / 2   
  
  #get S 
  library(Matrix)   
  U1 <- kronecker(diag(b1),matrix(1,n2,1))
  S <- diag(b1 * n2) + (1 * U1 %*% t(U1)) + (1 * U2 %*% t(U2)) # 2 is from paper
  
  x <- as.matrix(cbind(primary,potential.adj))  
  K <- diag(c(rep(0,p1),rep(1,p2)))
  if(qr(primary)$rank==p1){
        bd<-det(t(x)%*%solve(S)%*%x+K/tau^2)	^(1/(p1+p2))
       #bd<-1/tr(solve(t(x)%*%solve(S)%*%x+K/tau^2))		        
	}else{
		bd<-0
	}	
  #bd <- det(t(x)%*%x + K/tau^2)^(1/(p1+p2))
  return(bd)
}
```

```{r}
generateSLD <- function(m1, m2, m3, b1, n2){
  tem.w1 <- rep(c(-1, 1), each = b1/2)
  tem.w2 <- rep(c(-1, 1), each = b1/2)
  tem.s <- rep(c(-1, 1), each = b1*n2/2)
  wholeplot1 <- matrix(0, b1*n2, m1)
  wholeplot2 <- matrix(0, b1*n2, m2)
  subplot <- matrix(0, b1*n2, m3)
  
  for(i in 1:m1){
    wholeplot1[ ,i] <- rep(sample(tem.w1,b1), each = n2)  
  }
  
  for(i in 1:m2){
    wholeplot2[ ,i] <- rep(sample(tem.w1,b1), each = n2)
  }
  tem <- wholeplot2[1:(n2/2),]
  wholeplot2 <- wholeplot2[-c(1:(n2/2)),]
  wholeplot2 <- rbind(wholeplot2, tem)
  
  for(i in 1:m3){
    subplot[,i] <- sample(tem.s,b1*n2)
  }
  return(cbind(wholeplot1,wholeplot2, subplot))
}
```

```{r}
deleteOperation <- function(design, U2, b1, n2, m1, m2, m3, k){
  #k is number of delete columns
  tem.m1 <- m1
  tem.m2 <- m2
  tem.m3 <- m3
  delete.column.m1 <- c()
  delete.column.m2 <- c()
  delete.column.m3 <- c()
  for(i in 1:k){
    delete.value <- numeric(ncol(design))
    for(j in 1:ncol(design)){
      delete.value[j] <- evaluateMBayesianD(MSSD = design[,-j], U2 = U2, b1 =b1, n2 = n2)  
    }
    if(which.max(delete.value) <= tem.m1){
      delete.column.m1 <- cbind(delete.column.m1, design[,which.max(delete.value)])
      tem.m1 <- tem.m1 - 1
    }else if(which.max(delete.value) > tem.m1 + tem.m2){
      delete.column.m3 <- cbind(delete.column.m3, design[,which.max(delete.value)])
      tem.m3 <- tem.m3 - 1
    }else{
      delete.column.m2 <- cbind(delete.column.m2, design[,which.max(delete.value)])
      tem.m2 <- tem.m2 -1
    }
    design <- design[,-which.max(delete.value)]
  }
  
  number.remain.column <- c(tem.m1, tem.m2, tem.m3)
  print(number.remain.column)
  return(list(design = design,
              number.remain.column = number.remain.column,
              delete.column.m1 = delete.column.m1,
              delete.column.m2 = delete.column.m2,
              delete.column.m3 = delete.column.m3))
}
```

```{r}
#radom
deleteOperation <- function(design, U2, b1, n2, m1, m2, m3, k){
  #k is number of delete columns
  tem.m1 <- m1
  tem.m2 <- m2
  tem.m3 <- m3
  delete.column.m1 <- c()
  delete.column.m2 <- c()
  delete.column.m3 <- c()
  #radom
  y <- 0
  while(y == 0){
    replace.w <- rbinom(n = 2, size = k, prob = 0.1)
    if(sum(replace.w) <= k){
      y <- 1  
    }
  }
  replace.s <- k - replace.w[1] - replace.w[2]
  #print(c(replace.w,replace.s))
  #w1
  if(replace.w[1] != 0){
    for(i in 1:replace.w[1]){
      delete.value <- numeric(tem.m1) 
      for(j in 1:tem.m1){
        delete.value[j] <- evaluateMBayesianD(MSSD = design[,-j], U2 = U2, b1 =b1, n2 = n2)  
      }
      delete.column.m1 <- cbind(delete.column.m1, design[,which.max(delete.value)])
      design <- design[,-which.max(delete.value)]
      tem.m1 <- tem.m1 - 1
    }
  }
  
  #w2
  if(replace.w[2] != 0){
    for(i in 1:replace.w[2]){
      delete.value <- numeric(tem.m2) 
      for(j in 1:tem.m2){
        delete.value[j] <- evaluateMBayesianD(MSSD = design[,-(tem.m1+j)], U2 = U2, b1 =b1, n2 = n2)  
      }
      delete.column.m2 <- cbind(delete.column.m2, design[,which.max(delete.value)])
      design <- design[,-(tem.m1+which.max(delete.value))] 
      tem.m2 <- tem.m2 - 1
    }
  }
  
  #s
  if(replace.s != 0){
    for(i in 1:replace.s){
      delete.value <- numeric(tem.m3) 
      for(j in 1:tem.m3){
        delete.value[j] <- evaluateMBayesianD(MSSD = design[,-(tem.m1+tem.m2+j)], U2 = U2, b1 =b1, n2 = n2)  
      }
      delete.column.m3 <- cbind(delete.column.m3, design[,which.max(delete.value)])
      #print(delete.value)
      #print(tem.m1+tem.m2+which.max(delete.value))
      design <- design[,-(tem.m1+tem.m2+which.max(delete.value))] 
      tem.m3 <- tem.m3 - 1
    }
  }
  
  
  # for(i in 1:k){
  #   delete.value <- numeric(ncol(design))
  #   
  #   for(j in 1:ncol(design)){
  # 
  #     delete.value[j] <- evaluateMBayesianD(MSSD = design[,-j], U2 = U2, b1 =b1, n2 = n2)  
  #   }
  #   if(which.max(delete.value) <= tem.m1){
  #     delete.column.m1 <- cbind(delete.column.m1, design[,which.max(delete.value)])
  #     tem.m1 <- tem.m1 - 1
  #   }else if(which.max(delete.value) > tem.m1 + tem.m2){
  #     delete.column.m3 <- cbind(delete.column.m3, design[,which.max(delete.value)])
  #     tem.m3 <- tem.m3 - 1
  #   }else{
  #     delete.column.m2 <- cbind(delete.column.m2, design[,which.max(delete.value)])
  #     tem.m2 <- tem.m2 -1
  #   }
  #   design <- design[,-which.max(delete.value)]
  # }
  # 
  number.remain.column <- c(tem.m1, tem.m2, tem.m3)
  #print(ncol(design))
  return(list(design = design,
              number.remain.column = number.remain.column,
              delete.column.m1 = delete.column.m1,
              delete.column.m2 = delete.column.m2,
              delete.column.m3 = delete.column.m3))
}
```

```{r}
adjustOperation <- function(column.m1, column.m2, column.m3, b1, n2){
  column <- list(column.m1 = column.m1,
                 column.m2 = column.m2,
                 column.m3 = column.m3)
  
  candidate <- list()
  
  for(l in 1:3){
    tem.candidate <- c()
    if(typeof(column[[l]]) != "NULL"){
      if(l == 1){
        working.column <- matrix(0,b1,ncol(column[[l]]))
        for(i in 1:b1){
          working.column[i,] <- column[[l]][i*n2-(n2-1),]    
        }
          
      }else if(l == 2){
        working.column <- matrix(0,b1,ncol(column[[l]])) 
        for(i in 1:b1){
          working.column[i,] <- column[[l]][i*n2-(n2-1)+(n2/2),]    
        }
      }else{
        working.column <- column[[l]]  
      }
      
      
      for(i in 1:ncol(working.column)){
        adjust.column <- working.column[,i]
        positive.index <- which(adjust.column == 1)
        nagtive.index <- which(adjust.column == -1)
        
        for(j in 1:((nrow(working.column))/2)){
          for(k in 1:((nrow(working.column))/2)){
            tem.column <- adjust.column
            
            #1 to -1
            tem.column[positive.index[j]] <- -1
            
            #-1 to 1
            tem.column[nagtive.index[k]] <- 1
            
            if(l == 1){
              tem.candidate <- cbind(tem.candidate, rep(tem.column, each = n2))    
            }else if(l == 2){
              tem <- rep(tem.column,each = n2)
              tem.candidate <- cbind(tem.candidate, c(tem[(length(tem)-(n2/2)+1):length(tem)],tem[1:(length(tem)-(n2/2))]))
            }else{
              tem.candidate <- cbind(tem.candidate, tem.column)  
            }
          }  
        }
      }
      colnames(tem.candidate) <- NULL
      candidate[[l]] <- tem.candidate  
      
      
    }else{
      candidate[[l]] <- NA
    }
    
  }    
  
  
  return(candidate)
}
```

```{r}
addOperation <- function(design,candidate.set,m1,m2,m3,b1,n2,number.remain.column){
  number.add.column <- c(m1 - number.remain.column[1],
                         m2 - number.remain.column[2],
                         m3 - number.remain.column[3])
  
  for(l in 1:3){
    if(typeof(candidate.set[[l]]) == "double"){
      for(i in 1:number.add.column[l]){
        
        # eval add.value
        add.value <- numeric(ncol(candidate.set[[l]]))
        for(j in 1:ncol(candidate.set[[l]])){
          if(l == 1){
            add.value[j] <- evaluateMBayesianD(cbind(candidate.set[[l]][,i], design),
                                              U2 = U2,
                                              b1 = b1,
                                              n2 = n2)
            
          }else if(l == 2){
            add.value[j] <-  evaluateMBayesianD(cbind(design[,1:number.remain.column[1]], candidate.set[[l]][,i], design[,(number.remain.column[1]+1):sum(number.remain.column)]),U2 = U2,b1 = b1,n2=n2)
          }else{
            add.value[j] <- evaluateMBayesianD(cbind(design, candidate.set[[l]][,i]),U2 = U2,b1 = b1,n2=n2)  
          }
          
          
        }
        
        # add column
        if(l == 1){
          design <- cbind(candidate.set[[l]][, which.max(add.value)],design)  
        }else if(l == 2){
          design <- cbind(design[,1:number.remain.column[1]], 
                        candidate.set[[l]][,which.max(add.value)], 
                        design[,(number.remain.column[1]+1):sum(number.remain.column)])
        }else{
          design <- cbind(design, candidate.set[[l]][, which.max(add.value)])
        }
        number.remain.column[l] <- number.remain.column[l] + 1
        candidate.set[[l]] <- candidate.set[[l]][, -which.max(add.value)]
      }
    }
  }
  
  
  return(list(design = design, value = max(add.value)))
}
```
