---
title: "CP_staggered-level_BayesianD"
output: html_document
---
#Notation
m1 class-1 whole-plot factors,
m2 class-2 whole-plot factors,
m3 subplot factors,
b1 is the number of class-1 whole plots,
b2 = b1+1 is the number of class-2 whole plots,
b3 is the number of subplots,
n2 is the size of each class-1 whole plot,
n = b1*n2 = b3.

#k < min{m1,m2,m3}
```{r}
source_rmd <- function(file, local = FALSE, ...){
  options(knitr.duplicate.label = 'allow')

  tempR <- tempfile(tmpdir = ".", fileext = ".R")
  on.exit(unlink(tempR))
  knitr::purl(file, output=tempR, quiet = TRUE)

  envir <- globalenv()
  source(tempR, local = envir, ...)
}

Sys.setlocale('LC_ALL','C')
source_rmd("D:/statisic/Master_thesis/CP_staggered-level_BayesianD/CP_staggered-level_BayesianD_functions.Rmd")
```
```{r}
m1 <- 7
m2 <- 7
m3 <- 8
b1 <- 6
b2 <- 7
b3 <- 24
n <- 24
n2 <- 4

# get U2
U2 <- matrix(0, b1*n2, b2)
U2[1:(n2/2),1] <- 1
U2[(n2/2+(b1*n2-n2)+1):(b1*n2),ncol(U2)] <- 1
U2[((n2/2)+1):(n2/2+(b1*n2-n2)),2:(1+(b2-2))] <- kronecker(diag(b2-2),matrix(1,n2,1))

table8 <- as.matrix(read.csv("D:/statisic/Master_thesis/CP_staggered-level_BayesianD/table8.csv",header = F))
```

# Df values
```{r}
Dcriterion_staggered(mSSD = table8, U2 = U2, f = 2, b1 = b1, n2 = n2)
Dcriterion_staggered(mSSD = table8, U2 = U2, f = 3, b1 = b1, n2 = n2)
Dcriterion_staggered(mSSD = table8, U2 = U2, f = 4, b1 = b1, n2 = n2)
Dcriterion_staggered(mSSD = table8, U2 = U2, f = 5, b1 = b1, n2 = n2)
```

# Bayesian D value
```{r}
evaluateMBayesianD(MSSD = table8, U2 = U2, b1 =b1, n2 = n2)
```


```{r}
CP_staggered_level_BayesianD <- function(starting.design,U2, m1, m2, m3, b1, n2, k){
  record <- c()
  for(i in 1:starting.design){

    # if(added.design$value > best.design$value){
    #   best.design <- added.design
    #   print(best.design)
    # }
    
    #1. Generate a balanced N*m SSDs
    tem.design <- generateSLD(m1 = m1, m2 = m2,m3 = m3, b1 = b1, n2 = n2)  
    BayesianD.value <- evaluateMBayesianD(MSSD = tem.design, U2 = U2, b1 =b1, n2 = n2)

    #5. Repeat steps 2,3,4 until no improvement can be made.
    progress <- 0
    while(progress == 0){
      
      #2. Delete k columns which have the smallest object value.(k=1)
      deleted.design <- deleteOperation(design = tem.design,
                                        U2 = U2, 
                                        b1 = b1,
                                        n2 = n2,
                                        m1 = m1,
                                        m2 = m2,
                                        m3 = m3,
                                        k = k)  
      
      #3. Adjust the delete columns as candidate set.(only first order)
      candidate.set <- adjustOperation(column.m1 = deleted.design$delete.column.m1,
                                       column.m2 = deleted.design$delete.column.m2,
                                       column.m3 = deleted.design$delete.column.m3,
                                       b1 = b1,
                                       n2 = n2)
      
      #4. Add column at the candidate set with the largest object value.
      added.design <- addOperation(design = deleted.design$design,
                                   candidate.set = candidate.set,
                                   m1 = m1,
                                   m2 = m2,
                                   m3 = m3,
                                   b1 = b1,
                                   n2 = n2,
                                   number.remain.column = deleted.design$number.remain.column)
      
      if(added.design$value > BayesianD.value){
        BayesianD.value <- added.design$value 
        tem.design <- added.design$design
      }else{
        progress <- 1    
      }
    }
    
    tryCatch({
      if(added.design$value > best.design$value){
        best.design <- added.design
        print(paste("iteration:",i))
        print(best.design)
        
      }
      }, error = function(err){
        best.design <<- added.design
      })
    record <- c(record,best.design$value)
    
  } 
  return(list(best.design = best.design,record = record))
}

```
#####start#####
#test
```{r}
library(tictoc)
tic()
m1 <- 7
m2 <- 7
m3 <- 8
b1 <- 6
b2 <- 7
b3 <- 24
n <- 24
n2 <- 4
starting.design <- 100000
#k <- round(m/3)
k=5
result <- CP_staggered_level_BayesianD(starting.design = starting.design,
                                       U2 = U2,
                                       m1 = m1,
                                       m2 = m2,
                                       m3 = m3,
                                       b1 = b1,
                                       n2 = n2,
                                       k = k)
toc()
```