---
title: "mSIBSSD_functions"
output: html_document
---
Denote m1 the number
of whole-plot factors, m2 the number of subplot factors, n1 the number of whole plots, n2
the number of subplots within each whole plot.
```{r}
generateMSSD <- function(m1, m2, n1, n2){
  tem <- rep(c(-1, 1), each = n2/2)
  wholeplot <- matrix(0, n1*n2, m1)
  subplot <- matrix(0, n1*n2, m2)
  
  for(i in 1:m1){
    wholeplot[ ,i] <- rep(sample(tem,n2), each = n2)  
  }
  
  for(i in 1:m2){
    for(j in 1:n1){
      subplot[(n2*j-(n2-1)):((n2*j-(n2-1))+n2-1),i] <- sample(tem,n2)     
    }
  }
  return(cbind(wholeplot, subplot))
}

```

```{r}
Dcriterion <- function(mSSD, f = f,m1 = m1, m2 = m2, n1 = n1,n2 = n2){
  index.matrix <- combn(ncol(mSSD), f)
  library(Matrix)   
  Z <- kronecker(diag(n1),matrix(1,n2,1))
  S <- diag(n1 * n2) + (1 * Z %*% t(Z))
  
  Df <- 0
  for(i in 1:ncol(index.matrix)){
    Xf <- cbind(1, mSSD[ ,index.matrix[,i]])
    Df <- Df + det(t(Xf) %*% solve(S) %*% Xf)^(1/(f+1))
  }
  return(Df / choose(ncol(mSSD), f))
}
```

#Dcriterion_add & Dcriterion_delete
when Dcriterion_delete the criterion the smaller the better
when Dcriterion_add the criterion the bigger the better
```{r}
Dcriterion_add_delete <- function(mSSD, column, f = f,m1 = m1, m2 = m2, n1 = n1,n2 = n2){
  index.matrix <- combn(ncol(mSSD), f-1)
  Df <- 0  
  library(Matrix)   
  Z <- kronecker(diag(n1),matrix(1,n2,1))
  S <- diag(n1 * n2) + (1 * Z %*% t(Z))
  for(i in 1:ncol(index.matrix)){
    Xf <- cbind(1, mSSD[ ,index.matrix[,i]])
    Xf <- cbind(Xf,column)
    Df <- Df + det(t(Xf) %*% solve(S) %*% Xf)^(1/(f+1))
  }
  return(Df)
}
```

###
m1 = 0?
###

```{r}

# mixOperation <- function(particle, mSIBSSD.list, LB, GB, qLB, qGB){
#   mixwLB <- list()
#   mixwGB <- list()
#   for(i in 1:particle){
#     worksheet <- mSIBSSD.list[[i]]
#     
#     ###mixwLB###
#     #column deletion step 
#     tem <- worksheet
#     tem.m1 <- m1
#     tem.m2 <- m2
#     lack.m1 <- 0
#     lack.m2 <- 0
#     for(j in 1:qLB){
#       lack.value <- numeric(ncol(tem))
#       for(k in 1:ncol(tem)){
#         if(k <= m1){
#           lack.value[k] <- Dcriterion(mSSD = tem[ ,-k], f = f,m1 = tem.m1 - 1, m2 = tem.m2, n1 = n1,n2 = n2)  
#         }else{
#           lack.value[k] <- Dcriterion(mSSD = tem[ ,-k], f = f,m1 = tem.m1 , m2 = tem.m2 - 1, n1 = n1,n2 = n2)  
#         }
#       }
#         
#       
#       if(which.max(lack.value) <= tem.m1){
#         tem <- tem[,-which.max(lack.value)] 
#         tem.m1 <- tem.m1 - 1 
#         lack.m1 <- lack.m1 + 1
#       }else{
#         tem <- tem[,-which.max(lack.value)] 
#         tem.m2 <- tem.m2 - 1 
#         lack.m2 <- lack.m2 + 1
#       }
#       
#     }
#     
#     
#     #column addition step
#     #wholeplot
#     add.matrix <- LB[[i]]$design
#     for(j in 1:lack.m1){
#       add.value.m1 <- numeric(m1)   
#       for(k in 1:m1){
#         
#         add.value[k] <- Dcriterion(mSSD = cbind(add.matrix[ ,k], tem), f = f,m1 = tem.m1 + 1, m2 = tem.m2, n1 = n1,n2 = n2)
#       }
#       tem <- cbind(add.matrix[,which.max(add.value)], tem)
#     }
#     
#     #subplot
#     for(j in 1:lack.m2){
#       add.value <- numeric(m2)   
#       for(k in 1:m2){
#         
#         add.value[k] <- Dcriterion(mSSD = cbind(add.matrix[ ,k], tem), f = f,m1 = tem.m1, m2 = tem.m2 + 1, n1 = n1,n2 = n2)
#       }
#       tem <- cbind(tem,add.matrix[,which.(add.value)])
#     }
#     
#     mixwLB[[i]] <- list(design = tem,value = evaluateEs2(tem))  #important value
#     
#     ###mixwGB###
#     #column deletion step 
#     tem <- worksheet
#     for(j in 1:qGB){
#       lack.value <- numeric(ncol(tem))
#       for(k in 1:ncol(tem)){
#         lack.value[k] <- evaluateEs2(tem[,-k])
#       }
#       tem <- tem[,-which.min(lack.value)]
#     }
#     
#     #column addition step
#     add.matrix <- GB$design
#     for(j in 1:qGB){
#       add.value <- numeric(ncol(tem))
#       for(k in 1:ncol(add.matrix)){
#         add.value[k] <- evaluateEs2(cbind(tem,add.matrix[,k]))
#       }
#       tem <- cbind(tem,add.matrix[,which.min(add.value)])
#       
#     }
#     
#     mixwGB[[i]] <- list(design = tem,value = evaluateEs2(tem))  #important value
#     
#     
#     #column addition step
#   }
#   return(list(mixwLB = mixwLB, mixwGB = mixwGB))
#   
# }
# 

```

#radom W or S
```{r}
mixOperation <- function(particle, mSIBSSD.list, w.ratio = 0.2, LB, GB, qLB, qGB){
  mixwLB <- list()
  mixwGB <- list()
  for(i in 1:particle){
    worksheet <- mSIBSSD.list[[i]]
    
    ###mixwLB###
    #column deletion step 
    tem <- worksheet
    tem.m1 <- m1
    tem.m2 <- m2

    
    #radom
    w.qLB <- rbinom(n = 1, size = qLB, prob = w.ratio)
    s.qLB <- qLB - w.qLB
    
    #wholeplot
    if(w.qLB != 0){
      for(j in 1:w.qLB){
        lack.value <- numeric(tem.m1)
        for(k in 1:tem.m1){
          lack.value[k] <- Dcriterion(mSSD = tem[ ,-k], f = f, m1 = tem.m1 - 1, m2 = tem.m2, n1 = n1,n2 = n2)  
        }  
        tem <- tem[,-which.max(lack.value)] 
        tem.m1 <- tem.m1 - 1 
        #lack.m1 <- lack.m1 + 1
      }
    }
    
    #subplot
    if(s.qLB != 0){
      for(j in 1:s.qLB){
        lack.value <- numeric(tem.m2)
        for(k in 1:tem.m2){
          lack.value[k] <- Dcriterion(mSSD = tem[ ,-(tem.m1 + k)], f = f, m1 = tem.m1, m2 = tem.m2 - 1, n1 = n1,n2 = n2)  
        }  
        tem <- tem[,-(tem.m1 + which.max(lack.value))] 
        tem.m2 <- tem.m2 - 1 
        #lack.m2 <- lack.m2 + 1
      }
    }
    

    
    #column addition step
    #wholeplot
    add.matrix <- LB[[i]]$design
    if(w.qLB != 0){
      for(j in 1:w.qLB){
        add.value <- numeric(m1)   
        for(k in 1:m1){
          
          add.value[k] <- Dcriterion(mSSD = cbind(add.matrix[ ,k], tem), f = f,m1 = tem.m1 + 1, m2 = tem.m2, n1 = n1,n2 = n2)
        }
        tem <- cbind(add.matrix[,which.max(add.value)], tem)
        tem.m1 <- tem.m1 + 1
      }
    }
    #subplot
    if(s.qLB != 0){
      for(j in 1:s.qLB){
        add.value <- numeric(m2)   
        for(k in 1:m2){
          
          add.value[k] <- Dcriterion(mSSD = cbind(add.matrix[ ,m1 + k], tem), f = f,m1 = tem.m1, m2 = tem.m2 + 1, n1 = n1,n2 = n2)
        }
        tem <- cbind(tem,add.matrix[,tem.m1 + which.max(add.value)])
        tem.m2 <- tem.m2 + 1
      }
    }
    
    ###
    mixwLB[[i]] <- list(design = tem,value = Dcriterion(mSSD = tem, f = f,m1 = m1, m2 = m2, n1 = n1,n2 = n2))  #important value
    ###
    
    ###mixwGB###
    #column deletion step 
    tem <- worksheet
    tem.m1 <- m1
    tem.m2 <- m2

    
    #radom
    w.qGB <- rbinom(n = 1, size = qGB, prob = w.ratio)
    s.qGB <- qGB - w.qGB
    
    #wholeplot
    if(w.qGB != 0){
      for(j in 1:w.qGB){
        lack.value <- numeric(tem.m1)
        for(k in 1:tem.m1){
          lack.value[k] <- Dcriterion(mSSD = tem[ ,-k], f = f, m1 = tem.m1 - 1, m2 = tem.m2, n1 = n1,n2 = n2)  
        }  
        tem <- tem[,-which.max(lack.value)] 
        tem.m1 <- tem.m1 - 1 
        #lack.m1 <- lack.m1 + 1
      }
    }
    
    #subplot
    if(s.qGB != 0){
      for(j in 1:s.qGB){
        lack.value <- numeric(tem.m2)
        for(k in 1:tem.m2){
          lack.value[k] <- Dcriterion(mSSD = tem[ ,-(tem.m1 + k)], f = f, m1 = tem.m1, m2 = tem.m2 - 1, n1 = n1,n2 = n2)  
        }  
        tem <- tem[,-(tem.m1 + which.max(lack.value))] 
        tem.m2 <- tem.m2 - 1 
        #lack.m2 <- lack.m2 + 1
      }
    }
    

    
    #column addition step
    #wholeplot
    add.matrix <- GB$design
    if(w.qGB != 0){
      for(j in 1:w.qGB){
        add.value <- numeric(m1)   
        for(k in 1:m1){
          
          add.value[k] <- Dcriterion(mSSD = cbind(add.matrix[ ,k], tem), f = f,m1 = tem.m1 + 1, m2 = tem.m2, n1 = n1,n2 = n2)
        }
        tem <- cbind(add.matrix[,which.max(add.value)], tem)
        tem.m1 <- tem.m1 + 1
      }
    }
    #subplot
    if(s.qGB != 0){
      for(j in 1:s.qGB){
        add.value <- numeric(m2)   
        for(k in 1:m2){
          
          add.value[k] <- Dcriterion(mSSD = cbind(add.matrix[ ,m1 + k], tem), f = f,m1 = tem.m1, m2 = tem.m2 + 1, n1 = n1,n2 = n2)
        }
        tem <- cbind(tem,add.matrix[,tem.m1 + which.max(add.value)])
        tem.m2 <- tem.m2 + 1
      }
    }
    
    ###
    mixwGB[[i]] <- list(design = tem,value = Dcriterion(mSSD = tem, f = f,m1 = m1, m2 = m2, n1 = n1,n2 = n2))  #important value    
    ###
  
    
    
    #column addition step
  }
  return(list(mixwLB = mixwLB, mixwGB = mixwGB))
  
}
```


```{r}
moveOperation <- function(particle, mSIBSSD.list, w.ratio, mixwLB, mixwGB, qLB, qGB){
  for(i in 1:particle){
    
    if(mixwGB[[i]]$value > mixwLB[[i]]$value && mixwGB[[i]]$value > Dcriterion(mSSD = mSIBSSD.list[[i]], f = f,m1 = m1, m2 = m2, n1 = n1,n2 = n2)){
      mSIBSSD.list[[i]] <- mixwGB[[i]]$design 
      
    }else if(mixwLB[[i]]$value > mixwGB[[i]]$value && mixwLB[[i]]$value > Dcriterion(mSSD = mSIBSSD.list[[i]], f = f,m1 = m1, m2 = m2, n1 = n1,n2 = n2)){
      mSIBSSD.list[[i]] <- mixwLB[[i]]$design  
      
    }else{
      #radom
      w.qLB <- rbinom(n = 1, size = qLB, prob = w.ratio)
      s.qLB <- qLB - w.qLB
      w.replace.index <- sample(m1,w.qLB)
      s.replace.index <- sample(m2,s.qLB)
      replace.matrix <- generateMSSD(m1 = m1, m2 = m2, n1 = n1, n2 = n2)
      
      #wholeplot
      if(w.qLB != 0){
        
        mSIBSSD.list[[i]][,w.replace.index] <- replace.matrix[,w.replace.index]  
      }
       
      #subplot
      if(s.qLB != 0){
        mSIBSSD.list[[i]][,m1+s.replace.index] <- replace.matrix[,m1+s.replace.index]  
      }
      
    }
  }
  return(mSIBSSD.list)
}
```

advance
```{r}
mixOperation <- function(particle, mSIBSSD.list, w.ratio = 0.2, LB, GB, qLB, qGB){
  mixwLB <- list()
  mixwGB <- list()
  for(i in 1:particle){
    worksheet <- mSIBSSD.list[[i]]
    
    ###mixwLB###
    #column deletion step 
    tem <- worksheet
    tem.m1 <- m1
    tem.m2 <- m2

    
    #radom
    w.qLB <- rbinom(n = 1, size = qLB, prob = w.ratio)
    s.qLB <- qLB - w.qLB
    
    #wholeplot
    if(w.qLB != 0){
      for(j in 1:w.qLB){
        lack.value <- numeric(tem.m1)
        for(k in 1:tem.m1){
          lack.value[k] <- Dcriterion_add_delete(mSSD = tem[ ,-k], column = tem[,k], f = f, m1 = tem.m1, m2 = tem.m2, n1 = n1,n2 = n2)  
        }  
        tem <- tem[,-which.min(lack.value)] 
        tem.m1 <- tem.m1 - 1 
        #lack.m1 <- lack.m1 + 1
      }
    }
    
    #subplot
    if(s.qLB != 0){
      for(j in 1:s.qLB){
        lack.value <- numeric(tem.m2)
        for(k in 1:tem.m2){
          lack.value[k] <- Dcriterion_add_delete(mSSD = tem[ ,-(tem.m1 + k)],column = tem[,tem.m1 + k], f = f, m1 = tem.m1, m2 = tem.m2, n1 = n1,n2 = n2)  
        }  
        tem <- tem[,-(tem.m1 + which.min(lack.value))] 
        tem.m2 <- tem.m2 - 1 
        #lack.m2 <- lack.m2 + 1
      }
    }
    

    
    #column addition step
    #wholeplot
    add.matrix <- LB[[i]]$design
    if(w.qLB != 0){
      for(j in 1:w.qLB){
        add.value <- numeric(m1)   
        for(k in 1:m1){
          
          add.value[k] <- Dcriterion_add_delete(mSSD = tem, column = add.matrix[ ,k], f = f,m1 = tem.m1 , m2 = tem.m2, n1 = n1,n2 = n2)
        }
        tem <- cbind(add.matrix[,which.max(add.value)], tem)
        tem.m1 <- tem.m1 + 1
      }
    }
    #subplot
    if(s.qLB != 0){
      for(j in 1:s.qLB){
        add.value <- numeric(m2)   
        for(k in 1:m2){
          
          add.value[k] <- Dcriterion_add_delete(mSSD = tem, column = add.matrix[ ,m1 + k], f = f,m1 = tem.m1, m2 = tem.m2, n1 = n1,n2 = n2)
        }
        tem <- cbind(tem,add.matrix[,tem.m1 + which.max(add.value)])
        tem.m2 <- tem.m2 + 1
      }
    }
    
    ###
    mixwLB[[i]] <- list(design = tem,value = Dcriterion(mSSD = tem, f = f,m1 = m1, m2 = m2, n1 = n1,n2 = n2))  #important value
    ###
    
    ###mixwGB###
    #column deletion step 
    tem <- worksheet
    tem.m1 <- m1
    tem.m2 <- m2

    
    #radom
    w.qGB <- rbinom(n = 1, size = qGB, prob = w.ratio)
    s.qGB <- qGB - w.qGB
    
    #wholeplot
    if(w.qGB != 0){
      for(j in 1:w.qGB){
        lack.value <- numeric(tem.m1)
        for(k in 1:tem.m1){
          lack.value[k] <- Dcriterion_add_delete(mSSD = tem[ ,-k], column = tem[,k], f = f, m1 = tem.m1, m2 = tem.m2, n1 = n1,n2 = n2)  
        }  
        tem <- tem[,-which.min(lack.value)] 
        tem.m1 <- tem.m1 - 1 
        #lack.m1 <- lack.m1 + 1
      }
    }
    
    #subplot
    if(s.qGB != 0){
      for(j in 1:s.qGB){
        lack.value <- numeric(tem.m2)
        for(k in 1:tem.m2){
          lack.value[k] <- Dcriterion_add_delete(mSSD = tem[ ,-(tem.m1 + k)],column = tem[,tem.m1 + k], f = f, m1 = tem.m1, m2 = tem.m2, n1 = n1,n2 = n2)  
        }  
        tem <- tem[,-(tem.m1 + which.min(lack.value))] 
        tem.m2 <- tem.m2 - 1 
        #lack.m2 <- lack.m2 + 1
      }
    }
    

    
    #column addition step
    #wholeplot
    add.matrix <- GB$design
    if(w.qGB != 0){
      for(j in 1:w.qGB){
        add.value <- numeric(m1)   
        for(k in 1:m1){
          add.value[k] <- Dcriterion_add_delete(mSSD = tem, column = add.matrix[ ,k], f = f,m1 = tem.m1 , m2 = tem.m2, n1 = n1,n2 = n2) 
        }
        tem <- cbind(add.matrix[,which.max(add.value)], tem)
        tem.m1 <- tem.m1 + 1
      }
    }
    #subplot
    if(s.qGB != 0){
      for(j in 1:s.qGB){
        add.value <- numeric(m2)   
        for(k in 1:m2){
          
          add.value[k] <- Dcriterion_add_delete(mSSD = tem, column = add.matrix[ ,m1 + k], f = f,m1 = tem.m1, m2 = tem.m2, n1 = n1,n2 = n2)
        }
        tem <- cbind(tem,add.matrix[,tem.m1 + which.max(add.value)])
        tem.m2 <- tem.m2 + 1
      }
    }
    
    ###
    mixwGB[[i]] <- list(design = tem,value = Dcriterion(mSSD = tem, f = f,m1 = m1, m2 = m2, n1 = n1,n2 = n2))  #important value    
    ###
  
    
    
    #column addition step
  }
  return(list(mixwLB = mixwLB, mixwGB = mixwGB))
  
}
```


