---
title: "staggered-level_MSIBSSD_Df_functions"
output: html_document
---
```{r}
Dcriterion_staggered <- function(MSSD, U2, f = f, b1 = b1, n2 = n2){
  index.matrix <- combn(ncol(MSSD), f)
  library(Matrix)   
  U1 <- kronecker(diag(b1),matrix(1,n2,1))
  S <- diag(b1 * n2) + (1 * U1 %*% t(U1)) + (1 * U2 %*% t(U2)) # 1 is from paper
  
  Df <- 0
  for(i in 1:ncol(index.matrix)){
    Xf <- cbind(1, MSSD[ ,index.matrix[,i]])
    #Df <- Df + det(t(Xf) %*% solve(S) %*% Xf)^(1/(f+1))
    Df <- Df + round(det(t(Xf) %*% solve(S) %*% Xf),6)^(1/(f+1))
  }
  return(Df / choose(ncol(MSSD), f))
}
```

# Dcriterion_add & Dcriterion_delete
when Dcriterion_delete the criterion the smaller the better
when Dcriterion_add the criterion the bigger the better
```{r}
Dcriterion_add_delete <- function(MSSD, column, U2 = U2, f = f, b1 = b1, n2 = n2){
  index.matrix <- combn(ncol(MSSD), f-1)
  Df <- 0  
  library(Matrix)   
  U1 <- kronecker(diag(b1),matrix(1,n2,1))
  S <- diag(b1 * n2) + (1 * U1 %*% t(U1)) + (1 * U2 %*% t(U2)) # 1 is from paper
  for(i in 1:ncol(index.matrix)){
    Xf <- cbind(1, MSSD[ ,index.matrix[,i]])
    Xf <- cbind(Xf,column)
    Df <- Df + det(t(Xf) %*% solve(S) %*% Xf)^(1/(f+1))
  }
  return(Df)
}
```

#consider intereaction
```{r}
Dcriterion_staggered <- function(MSSD, U2, f = f, b1 = b1, n2 = n2){
  # intereaction
  inter.index <- combn(ncol(MSSD),2)
  for(i in 1:ncol(inter.index)){
    MSSD <- cbind(MSSD, MSSD[,inter.index[1,i]] * MSSD[,inter.index[2,i]])
  }
  
  index.matrix <- combn(ncol(MSSD), f)
  library(Matrix)   
  U1 <- kronecker(diag(b1),matrix(1,n2,1))
  S <- diag(b1 * n2) + (1 * U1 %*% t(U1)) + (1 * U2 %*% t(U2)) # 1 is from paper
  
  Df <- 0
  for(i in 1:ncol(index.matrix)){
    Xf <- cbind(1, MSSD[ ,index.matrix[,i]])
    #Df <- Df + det(t(Xf) %*% solve(S) %*% Xf)^(1/(f+1))
    Df <- Df + round(det(t(Xf) %*% solve(S) %*% Xf),6)^(1/(f+1))
  }
  return(Df / choose(ncol(MSSD), f))
}
```

# Dcriterion_add & Dcriterion_delete
when Dcriterion_delete the criterion the smaller the better
when Dcriterion_add the criterion the bigger the better
```{r}
Dcriterion_add_delete <- function(MSSD, column, U2 = U2, f = f, b1 = b1, n2 = n2){
  # intereaction
  inter.index <- combn(ncol(MSSD),2)
  for(i in 1:ncol(inter.index)){
    MSSD <- cbind(MSSD, MSSD[,inter.index[1,i]] * MSSD[,inter.index[2,i]])
  }
  
  index.matrix <- combn(ncol(MSSD), f-1)
  Df <- 0  
  library(Matrix)   
  U1 <- kronecker(diag(b1),matrix(1,n2,1))
  S <- diag(b1 * n2) + (1 * U1 %*% t(U1)) + (1 * U2 %*% t(U2)) # 1 is from paper
  for(i in 1:ncol(index.matrix)){
    Xf <- cbind(1, MSSD[ ,index.matrix[,i]])
    Xf <- cbind(Xf,column)
    Df <- Df + det(t(Xf) %*% solve(S) %*% Xf)^(1/(f+1))
  }
  return(Df)
}
```
```{r}
evaluateMBayesianD <- function(MSSD, U2, b1 ,n2){
  tau <- sqrt(5)
  m <- ncol(MSSD)
  
  #primary
  primary <- matrix(1,nrow = nrow(MSSD),1)
  p1 <- ncol(primary)
  
  #potential
  potential <- MSSD
  p2 <- ncol(potential)
  potential.adj <- potential / 2   
  
  #get S 
  library(Matrix)   
  U1 <- kronecker(diag(b1),matrix(1,n2,1))
  S <- diag(b1 * n2) + (1 * U1 %*% t(U1)) + (1 * U2 %*% t(U2)) # 2 is from paper
  
  x <- as.matrix(cbind(primary,potential.adj))  
  K <- diag(c(rep(0,p1),rep(1,p2)))
  if(qr(primary)$rank==p1){
        bd<-det(t(x)%*%solve(S)%*%x+K/tau^2)	^(1/(p1+p2))
       #bd<-1/tr(solve(t(x)%*%solve(S)%*%x+K/tau^2))		        
	}else{
		bd<-0
	}	
  #bd <- det(t(x)%*%x + K/tau^2)^(1/(p1+p2))
  return(bd)
}
```

```{r}
generateSLD <- function(m1, m2, m3, b1, n2){
  tem.w1 <- rep(c(-1, 1), each = b1/2)
  tem.w2 <- rep(c(-1, 1), each = b1/2)
  tem.s <- rep(c(-1, 1), each = b1*n2/2)
  wholeplot1 <- matrix(0, b1*n2, m1)
  wholeplot2 <- matrix(0, b1*n2, m2)
  subplot <- matrix(0, b1*n2, m3)
  
  for(i in 1:m1){
    
    wholeplot1[ ,i] <- rep(sample(tem.w1,size = b1), each = n2)  
  }
  
  for(i in 1:m2){
    
    wholeplot2[ ,i] <- rep(sample(tem.w1,size = b1), each = n2)
  }
  tem <- wholeplot2[1:(n2/2),]
  wholeplot2 <- wholeplot2[-c(1:(n2/2)),]
  wholeplot2 <- rbind(wholeplot2, tem)
  
  for(i in 1:m3){
    
    subplot[,i] <- sample(tem.s,size = b1*n2)
  }
  return(cbind(wholeplot1,wholeplot2, subplot))
}
```

```{r}
mixOperation <- function(particle, U2, m1, m2, m3, b1, n2, mSIBSSD.list, w.ratio = 0.1, LB, GB, qLB, qGB){
  mixwLB <- list()
  mixwGB <- list()
  for(i in 1:particle){
    worksheet <- mSIBSSD.list[[i]]
    
    ###mixwLB###
    #column deletion step 
    tem <- worksheet
    tem.m1 <- m1
    tem.m2 <- m2
    tem.m3 <- m3

    #radom
    w.qLB <- rbinom(n = 2, size = qLB, prob = w.ratio)
    if(w.qLB[1] > m1-1){
      w.qLB[1] <- m1 - 1 
    }else if(w.qLB[2] > m2-1){
      w.qLB[2] <- m2 - 1
    }
    if(sum(w.qLB) > qLB){
      w.qLB[which.max(w.qLB)] <- max(w.qLB) - (sum(w.qLB)-qLB)
    }
    s.qLB <- qLB - w.qLB[1] -w.qLB[2]
    
    #wholeplot1
    if(w.qLB[1] != 0){
      for(j in 1:w.qLB[1]){
        lack.value <- numeric(tem.m1)
        for(k in 1:tem.m1){
          lack.value[k] <- Dcriterion_staggered(MSSD = tem[ ,-k], f = 2, U2 = U2, b1 = b1, n2 = n2)  
        }  
        tem <- tem[,-which.max(lack.value)] 
        tem.m1 <- tem.m1 - 1 
      }
    }
    
    #wholeplot2
    if(w.qLB[2] != 0){
      for(j in 1:w.qLB[2]){
        lack.value <- numeric(tem.m2)
        for(k in 1:tem.m2){
          lack.value[k] <- Dcriterion_staggered(MSSD = tem[ ,-(tem.m1 + k)], f = 2,U2 = U2, b1 = b1, n2 = n2)  
        }  
        tem <- tem[,-(tem.m1 + which.max(lack.value))] 
        tem.m2 <- tem.m2 - 1 
      }
    }
    
    #subplot
    if(s.qLB != 0){
      for(j in 1:s.qLB){
        lack.value <- numeric(tem.m3)
        for(k in 1:tem.m3){
          lack.value[k] <- Dcriterion_staggered(MSSD = tem[ ,-(tem.m1 + tem.m2 + k)], f = 2, U2 = U2, b1 = b1, n2 = n2)  
        }  
        tem <- tem[,-(tem.m1 + tem.m2 + which.max(lack.value))] 
        tem.m3 <- tem.m3 - 1 
      }
    }
     
   
    
    #column addition step
    add.matrix <- LB[[i]]$design
   
    #wholeplot1
    if(w.qLB[1] != 0){
      for(j in 1:w.qLB[1]){
        add.value <- numeric(m1)   
        for(k in 1:m1){
          
          add.value[k] <- Dcriterion_staggered(MSSD = cbind(add.matrix[ ,k], tem),f = 1, U2 = U2, b1 = b1, n2 = n2)
        }
        tem <- cbind(add.matrix[,which.max(add.value)], tem)
        
      }
    }
   
    #wholeplot2
    if(w.qLB[2] != 0){
      for(j in 1:w.qLB[2]){
        add.value <- numeric(m2)   
        for(k in 1:m2){
          
          add.value[k] <- Dcriterion_staggered(MSSD = cbind(tem[,1:m1],add.matrix[ ,m1 +k], tem[,(m1+1):ncol(tem)]), f = 2 , U2 = U2, b1 = b1, n2 = n2)
        }
        tem <- cbind(tem[,1:m1], add.matrix[,m1 + which.max(add.value)], tem[,(m1+1) :ncol(tem)])
        
      }
    }
    
    #subplot
    if(s.qLB != 0){
      for(j in 1:s.qLB){
        add.value <- numeric(m3)   
        for(k in 1:m3){
          
          add.value[k] <- Dcriterion_staggered(MSSD = cbind(tem, add.matrix[ ,m1 +m2 +k]), f = 2 ,U2 = U2, b1 = b1, n2 = n2)
        }
        tem <- cbind(tem,add.matrix[,m1 + m2 + which.max(add.value)])
      }
    }
  
    ###
    mixwLB[[i]] <- list(design = tem,value = Dcriterion_staggered(MSSD = tem, f = 2, U2 = U2, b1 = b1, n2 = n2))  #important value
    ###
    
    ###mixwGB###
    #column deletion step 
    tem <- worksheet
    tem.m1 <- m1
    tem.m2 <- m2
    tem.m3 <- m3

    
    #radom
    w.qGB <- rbinom(n = 2, size = qGB, prob = w.ratio)
    if(w.qGB[1] > m1 -1){
      w.qGB[1] <- m1 -1  
    }else if(w.qGB[2] > m2 -1){
      w.qGB[2] <- m2 -1
    }
    if(sum(w.qGB) > qGB){
      w.qGB[which.max(w.qGB)] <- max(w.qGB) - (sum(w.qGB)-qGB)
    }
    s.qGB <- qGB - w.qGB[1] - w.qGB[2]
    
    
    #wholeplot1
    if(w.qGB[1] != 0){
      for(j in 1:w.qGB[1]){
        lack.value <- numeric(tem.m1)
        for(k in 1:tem.m1){
          lack.value[k] <- Dcriterion_staggered(MSSD = tem[ ,-k], f = 2, U2 = U2, b1 = b1, n2 = n2)  
        }  
        tem <- tem[,-which.max(lack.value)] 
        tem.m1 <- tem.m1 - 1 
        
      }
    }
    
    #wholeplot2
    if(w.qGB[2] != 0){
      for(j in 1:w.qGB[2]){
        lack.value <- numeric(tem.m2)
        for(k in 1:tem.m2){
          lack.value[k] <- Dcriterion_staggered(MSSD = tem[ ,-(tem.m1 + k)], f = 2, U2 = U2, b1 = b1, n2 = n2)  
        }  
        tem <- tem[,-(tem.m1 + which.max(lack.value))] 
        tem.m2 <- tem.m2 - 1 
      }
    }
    
    #subplot
    if(s.qGB != 0){
      for(j in 1:s.qGB){
        lack.value <- numeric(tem.m3)
        for(k in 1:tem.m3){
          lack.value[k] <- Dcriterion_staggered(MSSD = tem[ ,-(tem.m1 + tem.m2 + k)], f = 2, U2 = U2, b1 = b1, n2 = n2)  
        }  
        tem <- tem[,-(tem.m1 + tem.m2 + which.max(lack.value))] 
        tem.m3 <- tem.m3 - 1 
      }
    }
    

    
    #column addition step
    add.matrix <- GB$design
    
    #wholeplot1
    if(w.qGB[1] != 0){
      for(j in 1:w.qGB[1]){
        add.value <- numeric(m1)   
        for(k in 1:m1){
          
          add.value[k] <- Dcriterion_staggered(MSSD = cbind(add.matrix[ ,k], tem), f = 2, U2 = U2, b1 = b1, n2 = n2)
        }
        tem <- cbind(add.matrix[,which.max(add.value)], tem)
      }
    }
    
    #wholeplot2
    add.matrix <- LB[[i]]$design
    if(w.qGB[2] != 0){
      for(j in 1:w.qGB[2]){
        add.value <- numeric(m2)   
        for(k in 1:m2){
          
          add.value[k] <- Dcriterion_staggered(MSSD = cbind(tem[,1:m1],add.matrix[ ,m1 +k], tem[,(m1+1):ncol(tem)]), f = 2, U2 = U2, b1 = b1, n2 = n2)
        }
        tem <- cbind(tem[,1:m1], add.matrix[,m1 + which.max(add.value)], tem[,(m1+1) :ncol(tem)])
        
      }
    }
    
    #subplot
    if(s.qGB != 0){
      for(j in 1:s.qGB){
        add.value <- numeric(m3)   
        for(k in 1:m3){
          
          add.value[k] <- Dcriterion_staggered(MSSD = cbind(tem, add.matrix[ ,m1 +m2 +k]), f = 2, U2 = U2, b1 = b1, n2 = n2)
        }
        tem <- cbind(tem,add.matrix[,m1 + m2 + which.max(add.value)])
      }
    }
   
    ###
    mixwGB[[i]] <- list(design = tem,value = Dcriterion_staggered(MSSD = tem, f = 2, U2 = U2, b1 = b1, n2 = n2))  #important value    
    ###
  
    
    
    #column addition step
  }
  return(list(mixwLB = mixwLB, mixwGB = mixwGB))
  
}
```

#advance
```{r}
mixOperation <- function(particle, U2, f=2, m1, m2, m3, b1, n2, mSIBSSD.list, w.ratio = 0.1, LB, GB, qLB, qGB){
  mixwLB <- list()
  mixwGB <- list()
  for(i in 1:particle){
    worksheet <- mSIBSSD.list[[i]]
    
    ###mixwLB###
    #column deletion step 
    tem <- worksheet
    tem.m1 <- m1
    tem.m2 <- m2
    tem.m3 <- m3

    #radom
    y <- 0
    while(y == 0){
      w.qLB <- rbinom(n = 2, size = qLB, prob = w.ratio) 
      if(w.qLB[1] <= m1-1 && w.qLB[2] <= m2-1 && sum(w.qLB) <= qLB){
        y <- 1
      }
    }
    s.qLB <- qLB - w.qLB[1] -w.qLB[2]
    
    #wholeplot1
    if(w.qLB[1] != 0){
      for(j in 1:w.qLB[1]){
        lack.value <- numeric(tem.m1)
        for(k in 1:tem.m1){
          #lack.value[k] <- Dcriterion_staggered(MSSD = tem[ ,-k], f = 2, U2 = U2, b1 = b1, n2 = n2)  
          lack.value[k] <- Dcriterion_add_delete(MSSD = tem[ ,-k], column = tem[,k], U2 = U2, f = f, b1 = b1, n2 = n2)
        }  
        tem <- tem[,-which.min(lack.value)] 
        tem.m1 <- tem.m1 - 1 
      }
    }
    
    #wholeplot2
    if(w.qLB[2] != 0){
      for(j in 1:w.qLB[2]){
        lack.value <- numeric(tem.m2)
        for(k in 1:tem.m2){
          #lack.value[k] <- Dcriterion_staggered(MSSD = tem[ ,-(tem.m1 + k)], f = 2,U2 = U2, b1 = b1, n2 = n2)  
          lack.value[k] <- Dcriterion_add_delete(MSSD = tem[ ,-(tem.m1 + k)], column = tem[,(tem.m1 + k)], U2 = U2, f = f, b1 = b1, n2 = n2)
        }  
        tem <- tem[,-(tem.m1 + which.min(lack.value))] 
        tem.m2 <- tem.m2 - 1 
      }
    }
    
    #subplot
    if(s.qLB != 0){
      for(j in 1:s.qLB){
        lack.value <- numeric(tem.m3)
        for(k in 1:tem.m3){
          #lack.value[k] <- Dcriterion_staggered(MSSD = tem[ ,-(tem.m1 + tem.m2 + k)], f = 2, U2 = U2, b1 = b1, n2 = n2)  
          lack.value[k] <- Dcriterion_add_delete(MSSD = tem[ ,-(tem.m1 + tem.m2 + k)], column = tem[,(tem.m1 + tem.m2 + k)], U2 = U2, f = f, b1 = b1, n2 = n2)
        }  
        tem <- tem[,-(tem.m1 + tem.m2 + which.min(lack.value))] 
        tem.m3 <- tem.m3 - 1 
      }
    }
     
   
    
    #column addition step
    add.matrix <- LB[[i]]$design
   
    #wholeplot1
    if(w.qLB[1] != 0){
      for(j in 1:w.qLB[1]){
        add.value <- numeric(m1)   
        for(k in 1:m1){
          
          #add.value[k] <- Dcriterion_staggered(MSSD = cbind(add.matrix[ ,k], tem),f = 1, U2 = U2, b1 = b1, n2 = n2)
          add.value[k] <- Dcriterion_add_delete(MSSD = tem, column = add.matrix[,k], U2 = U2, f = f, b1 = b1, n2 = n2)
        }
        tem <- cbind(add.matrix[,which.max(add.value)], tem)
        
      }
    }
   
    #wholeplot2
    if(w.qLB[2] != 0){
      for(j in 1:w.qLB[2]){
        add.value <- numeric(m2)   
        for(k in 1:m2){
          
          #add.value[k] <- Dcriterion_staggered(MSSD = cbind(tem[,1:m1],add.matrix[ ,m1 +k], tem[,(m1+1):ncol(tem)]), f = 2 , U2 = U2, b1 = b1, n2 = n2)
          add.value[k] <- Dcriterion_add_delete(MSSD = tem, column = add.matrix[,m1 +k], U2 = U2, f = f, b1 = b1, n2 = n2)
        }
        tem <- cbind(tem[,1:m1], add.matrix[,m1 + which.max(add.value)], tem[,(m1+1) :ncol(tem)])
        
      }
    }
    
    #subplot
    if(s.qLB != 0){
      for(j in 1:s.qLB){
        add.value <- numeric(m3)   
        for(k in 1:m3){
          
          #add.value[k] <- Dcriterion_staggered(MSSD = cbind(tem, add.matrix[ ,m1 +m2 +k]), f = 2 ,U2 = U2, b1 = b1, n2 = n2)
          add.value[k] <- Dcriterion_add_delete(MSSD = tem, column = add.matrix[,m1 +m2 + k], U2 = U2, f = f, b1 = b1, n2 = n2)
        }
        tem <- cbind(tem,add.matrix[,m1 + m2 + which.max(add.value)])
      }
    }
  
    ###
    mixwLB[[i]] <- list(design = tem,value = Dcriterion_staggered(MSSD = tem, f = 2, U2 = U2, b1 = b1, n2 = n2))  #important value
    ###
    
    ###mixwGB###
    #column deletion step 
    tem <- worksheet
    tem.m1 <- m1
    tem.m2 <- m2
    tem.m3 <- m3

    
    #radom
    y <- 0
    while(y == 0){
      w.qGB <- rbinom(n = 2, size = qGB, prob = w.ratio) 
      if(w.qGB[1] <= m1-1 && w.qGB[2] <= m2-1 && sum(w.qGB) <= qGB){
        y <- 1
      }
    }
    s.qGB <- qGB - w.qGB[1] - w.qGB[2]
    
    
    #wholeplot1
    if(w.qGB[1] != 0){
      for(j in 1:w.qGB[1]){
        lack.value <- numeric(tem.m1)
        for(k in 1:tem.m1){
          #lack.value[k] <- Dcriterion_staggered(MSSD = tem[ ,-k], f = 2, U2 = U2, b1 = b1, n2 = n2)
          lack.value[k] <- Dcriterion_add_delete(MSSD = tem[ ,-k], column = tem[,k], U2 = U2, f = f, b1 = b1, n2 = n2)
        }  
        tem <- tem[,-which.min(lack.value)] 
        tem.m1 <- tem.m1 - 1 
        
      }
    }
    
    #wholeplot2
    if(w.qGB[2] != 0){
      for(j in 1:w.qGB[2]){
        lack.value <- numeric(tem.m2)
        for(k in 1:tem.m2){
          #lack.value[k] <- Dcriterion_staggered(MSSD = tem[ ,-(tem.m1 + k)], f = 2, U2 = U2, b1 = b1, n2 = n2)  
          lack.value[k] <- Dcriterion_add_delete(MSSD = tem[ ,-(tem.m1 + k)], column = tem[,(tem.m1 + k)], U2 = U2, f = f, b1 = b1, n2 = n2)
        }  
        tem <- tem[,-(tem.m1 + which.min(lack.value))] 
        tem.m2 <- tem.m2 - 1 
      }
    }
    
    #subplot
    if(s.qGB != 0){
      for(j in 1:s.qGB){
        lack.value <- numeric(tem.m3)
        for(k in 1:tem.m3){
          #lack.value[k] <- Dcriterion_staggered(MSSD = tem[ ,-(tem.m1 + tem.m2 + k)], f = 2, U2 = U2, b1 = b1, n2 = n2)  
          lack.value[k] <- Dcriterion_add_delete(MSSD = tem[ ,-(tem.m1 + k)], column = tem[,(tem.m1 + k)], U2 = U2, f = f, b1 = b1, n2 = n2)
        }  
        tem <- tem[,-(tem.m1 + tem.m2 + which.min(lack.value))] 
        tem.m3 <- tem.m3 - 1 
      }
    }
    

    
    #column addition step
    add.matrix <- GB$design
    
    #wholeplot1
    if(w.qGB[1] != 0){
      for(j in 1:w.qGB[1]){
        add.value <- numeric(m1)   
        for(k in 1:m1){
          
          #add.value[k] <- Dcriterion_staggered(MSSD = cbind(add.matrix[ ,k], tem), f = 2, U2 = U2, b1 = b1, n2 = n2)
          add.value[k] <- Dcriterion_add_delete(MSSD = tem, column = add.matrix[,k], U2 = U2, f = f, b1 = b1, n2 = n2)
        }
        tem <- cbind(add.matrix[,which.max(add.value)], tem)
      }
    }
    
    #wholeplot2
    if(w.qGB[2] != 0){
      for(j in 1:w.qGB[2]){
        add.value <- numeric(m2)   
        for(k in 1:m2){
          
          #add.value[k] <- Dcriterion_staggered(MSSD = cbind(tem[,1:m1],add.matrix[ ,m1 +k], tem[,(m1+1):ncol(tem)]), f = 2, U2 = U2, b1 = b1, n2 = n2)
          add.value[k] <- Dcriterion_add_delete(MSSD = tem, column = add.matrix[,m1 +k], U2 = U2, f = f, b1 = b1, n2 = n2)
        }
        tem <- cbind(tem[,1:m1], add.matrix[,m1 + which.max(add.value)], tem[,(m1+1) :ncol(tem)])
        
      }
    }
    
    #subplot
    if(s.qGB != 0){
      for(j in 1:s.qGB){
        add.value <- numeric(m3)   
        for(k in 1:m3){
          
          #add.value[k] <- Dcriterion_staggered(MSSD = cbind(tem, add.matrix[ ,m1 +m2 +k]), f = 2, U2 = U2, b1 = b1, n2 = n2)
          add.value[k] <- Dcriterion_add_delete(MSSD = tem, column = add.matrix[,m1 +m2 + k], U2 = U2, f = f, b1 = b1, n2 = n2)
        }
        tem <- cbind(tem,add.matrix[,m1 + m2 + which.max(add.value)])
      }
    }
   
    ###
    mixwGB[[i]] <- list(design = tem,value = Dcriterion_staggered(MSSD = tem, f = 2, U2 = U2, b1 = b1, n2 = n2))  #important value    
    ###
  
    
    
    #column addition step
  }
  return(list(mixwLB = mixwLB, mixwGB = mixwGB))
  
}
```
```{r}
moveOperation <- function(particle, U2, m1, m2, m3, b1, n2, mSIBSSD.list, w.ratio = w.ratio, mixwLB, mixwGB, qLB, qGB){
  for(i in 1:particle){
    
    if(mixwGB[[i]]$value > mixwLB[[i]]$value && mixwGB[[i]]$value > Dcriterion_staggered(MSSD = mSIBSSD.list[[i]], f = 2, U2 = U2, b1 = b1, n2 = n2)){
      mSIBSSD.list[[i]] <- mixwGB[[i]]$design 
      
    }else if(mixwLB[[i]]$value > mixwGB[[i]]$value && mixwLB[[i]]$value > Dcriterion_staggered(MSSD = mSIBSSD.list[[i]], f = 2, U2 = U2, b1 = b1, n2 = n2)){
      mSIBSSD.list[[i]] <- mixwLB[[i]]$design  
      
    }else{
      #radom
      y <- 0
      while(y == 0){
        w.qLB <- rbinom(n = 2, size = qLB, prob = w.ratio) 
        if(w.qLB[1] <= m1-1 && w.qLB[2] <= m2-1 && sum(w.qLB) <= qLB){
          y <- 1
        }
      }
      s.qLB <- qLB - w.qLB[1] -w.qLB[2]
      replace.matrix <- generateSLD(m1 = m1, m2 = m2, m3 = m3, b1 = b1, n2 = n2)
      
      #wholeplot1
      if(w.qLB[1] != 0){
        w1.replace.index <- sample(m1,size = w.qLB[1])
        mSIBSSD.list[[i]][,w1.replace.index] <- replace.matrix[,w1.replace.index]  
      }
       
      #wholeplot2
      if(w.qLB[2] != 0){
        w2.replace.index <- sample(m2,size = w.qLB[2])
        mSIBSSD.list[[i]][,m1+w2.replace.index] <- replace.matrix[,m1+w2.replace.index]  
      }
      
      #subplot
      if(s.qLB != 0){
        s.replace.index <- sample(m3,size = s.qLB)
        mSIBSSD.list[[i]][,m1+m2+s.replace.index] <- replace.matrix[,m1+m2+s.replace.index]  
      }
      
    }
  }
  return(mSIBSSD.list)
}
```
