---
title: "CP_BayesianD"
output: html_document
---
Algorithm :
1. Generate a balanced N*m SSDs
2. Delete k columns which have the smallest object value.(k=1)
3. Adjust the delete columns as candidate set.
4. Add column at the candidate set with the largest object value.
5. Repeat steps 2,3,4 until no improvement can be made.

#read functions
```{r}
source_rmd <- function(file, local = FALSE, ...){
  options(knitr.duplicate.label = 'allow')

  tempR <- tempfile(tmpdir = ".", fileext = ".R")
  on.exit(unlink(tempR))
  knitr::purl(file, output=tempR, quiet = TRUE)

  envir <- globalenv()
  source(tempR, local = envir, ...)
}
#read functions

Sys.setlocale('LC_ALL','C')
source_rmd("D:/statisic/Master_thesis/CP_BayesianD/CP_BayesianD_functions.Rmd")
```

```{r}
CP_BayesianD <- function(starting.design, N, m, k){
  
  for(i in 1:starting.design){

    # if(added.design$value > best.design$value){
    #   best.design <- added.design
    #   print(best.design)
    # }
    
    #1. Generate a balanced N*m SSDs
    tem.desgn <- generateSSD(N = N,m = m)  
    BayesianD.value <- evaluateBayesianD(tem.desgn)
    
    #5. Repeat steps 2,3,4 until no improvement can be made.
    progress <- 0
    while(progress == 0){
      
      #2. Delete k columns which have the smallest object value.(k=1)
      deleted.design <- deleteOperation(design = tem.desgn,k = k)  
      
      #3. Adjust the delete columns as candidate set.(only first order)
      candidate.set <- adjustOperation(column = deleted.design$delete.column)
      
      #4. Add column at the candidate set with the largest object value.
      added.design <- addOperation(design = deleted.design$design, candidate.set = candidate.set, k = k)
      
      if(added.design$value > BayesianD.value){
        BayesianD.value <- added.design$value 
        tem.desgn <- added.design$design
      }else{
        progress <- 1    
      }
    }
    tryCatch({
      if(added.design$value > best.design$value){
        best.design <- added.design
        print(best.design)
      }
      }, error = function(err) {
        best.design <<- added.design
      })
    
    
  } 
  return(best.design)
}

```

#####start#####
#test
```{r}
library(tictoc)
tic()
N <- 24
m <- 30
#k <- round(m/3)
k=1
result <- CP_BayesianD(starting.design = 1000000, N = N, m = m, k = k)
toc()
```
