---
title: "spilt-plot_MSIBSSD_BayesianD_functions"
output: html_document
---
Denote m1 the number
of whole-plot factors, m2 the number of subplot factors, n1 the number of whole plots, n2
the number of subplots within each whole plot.
```{r}
evaluateMBayesianD <- function(MSSD, n1 ,n2){
  tau <- sqrt(5)
  m <- ncol(MSSD)
  
  #primary
  primary <- matrix(1,nrow = nrow(MSSD),1)
  p1 <- ncol(primary)
  
  #potential
  potential <- MSSD
  p2 <- ncol(potential)
  potential.adj <- potential / 2   
  
  #get S 
  library(Matrix)   
  Z <- kronecker(diag(n1),matrix(1,n2,1))
  S <- diag(n1 * n2) + (1 * Z %*% t(Z))
  
  x <- as.matrix(cbind(primary,potential.adj))  
  K <- diag(c(rep(0,p1),rep(1,p2)))
  if(qr(primary)$rank==p1){
        bd<-det(t(x)%*%solve(S)%*%x+K/tau^2)	^(1/(p1+p2))
       #bd<-1/tr(solve(t(x)%*%solve(S)%*%x+K/tau^2))		        
	}else{
		bd<-0
	}	
  #bd <- det(t(x)%*%x + K/tau^2)^(1/(p1+p2))
  return(bd)
}
```

```{r}
generateMSSD <- function(m1, m2, n1, n2){
  tem <- rep(c(-1, 1), each = n2/2)
  wholeplot <- matrix(0, n1*n2, m1)
  subplot <- matrix(0, n1*n2, m2)
  
  for(i in 1:m1){
    wholeplot[ ,i] <- rep(sample(tem,n2), each = n2)  
  }
  
  for(i in 1:m2){
    for(j in 1:n1){
      subplot[(n2*j-(n2-1)):((n2*j-(n2-1))+n2-1),i] <- sample(tem,n2)     
    }
  }
  return(cbind(wholeplot, subplot))
}
```


```{r}
mixOperation <- function(particle, mSIBSSD.list, w.ratio = 0.2, LB, GB, qLB, qGB){
  mixwLB <- list()
  mixwGB <- list()
  for(i in 1:particle){
    worksheet <- mSIBSSD.list[[i]]
    
    ###mixwLB###
    #column deletion step 
    tem <- worksheet
    tem.m1 <- m1
    tem.m2 <- m2

    
    #radom
    w.qLB <- rbinom(n = 1, size = qLB, prob = w.ratio)
    s.qLB <- qLB - w.qLB
    
    #wholeplot
    if(w.qLB != 0){
      for(j in 1:w.qLB){
        lack.value <- numeric(tem.m1)
        for(k in 1:tem.m1){
          lack.value[k] <- evaluateMBayesianD(MSSD = tem[ ,-k], n1 = n1,n2 = n2)  
        }  
        tem <- tem[,-which.max(lack.value)] 
        tem.m1 <- tem.m1 - 1 
        #lack.m1 <- lack.m1 + 1
      }
    }
    
    #subplot
    if(s.qLB != 0){
      for(j in 1:s.qLB){
        lack.value <- numeric(tem.m2)
        for(k in 1:tem.m2){
          lack.value[k] <- evaluateMBayesianD(MSSD = tem[ ,-(tem.m1 + k)], n1 = n1,n2 = n2)  
        }  
        tem <- tem[,-(tem.m1 + which.max(lack.value))] 
        tem.m2 <- tem.m2 - 1 
        #lack.m2 <- lack.m2 + 1
      }
    }
    

    
    #column addition step
    #wholeplot
    add.matrix <- LB[[i]]$design
    if(w.qLB != 0){
      for(j in 1:w.qLB){
        add.value <- numeric(m1)   
        for(k in 1:m1){
          
          add.value[k] <- evaluateMBayesianD(MSSD = cbind(add.matrix[ ,k], tem), n1 = n1,n2 = n2)
        }
        tem <- cbind(add.matrix[,which.max(add.value)], tem)
        tem.m1 <- tem.m1 + 1
      }
    }
    #subplot
    if(s.qLB != 0){
      for(j in 1:s.qLB){
        add.value <- numeric(m2)   
        for(k in 1:m2){
          
          add.value[k] <- evaluateMBayesianD(MSSD = cbind(tem, add.matrix[ ,m1 + k]), n1 = n1,n2 = n2)
        }
        tem <- cbind(tem, add.matrix[,m1 + which.max(add.value)])
        tem.m2 <- tem.m2 + 1
      }
    }
    
    ###
    mixwLB[[i]] <- list(design = tem,value = evaluateMBayesianD(MSSD = tem,n1 = n1,n2 = n2))  #important value
    ###
    
    ###mixwGB###
    #column deletion step 
    tem <- worksheet
    tem.m1 <- m1
    tem.m2 <- m2

    
    #radom
    w.qGB <- rbinom(n = 1, size = qGB, prob = w.ratio)
    s.qGB <- qGB - w.qGB
    
    #wholeplot
    if(w.qGB != 0){
      for(j in 1:w.qGB){
        lack.value <- numeric(tem.m1)
        for(k in 1:tem.m1){
          lack.value[k] <- evaluateMBayesianD(MSSD = tem[ ,-k], n1 = n1,n2 = n2)  
        }  
        tem <- tem[,-which.max(lack.value)] 
        tem.m1 <- tem.m1 - 1 
        #lack.m1 <- lack.m1 + 1
      }
    }
    
    #subplot
    if(s.qGB != 0){
      for(j in 1:s.qGB){
        lack.value <- numeric(tem.m2)
        for(k in 1:tem.m2){
          lack.value[k] <- evaluateMBayesianD(MSSD = tem[ ,-(tem.m1 + k)], n1 = n1,n2 = n2)  
        }  
        tem <- tem[,-(tem.m1 + which.max(lack.value))] 
        tem.m2 <- tem.m2 - 1 
        #lack.m2 <- lack.m2 + 1
      }
    }
    

    
    #column addition step
    #wholeplot
    add.matrix <- GB$design
    if(w.qGB != 0){
      for(j in 1:w.qGB){
        add.value <- numeric(m1)   
        for(k in 1:m1){
          
          add.value[k] <- evaluateMBayesianD(MSSD = cbind(add.matrix[ ,k], tem), n1 = n1,n2 = n2)
        }
        tem <- cbind(add.matrix[,which.max(add.value)], tem)
      }
    }
    
    #subplot
    if(s.qGB != 0){
      for(j in 1:s.qGB){
        add.value <- numeric(m2)   
        for(k in 1:m2){
          
          add.value[k] <- evaluateMBayesianD(MSSD = cbind(tem, add.matrix[ ,m1 + k]), n1 = n1,n2 = n2)
        }
        tem <- cbind(tem, add.matrix[,m1 + which.max(add.value)])
      }
    }
    
    ###
    mixwGB[[i]] <- list(design = tem,value = evaluateMBayesianD(MSSD = tem, n1 = n1,n2 = n2))  #important value    
    ###
  
    
    
    #column addition step
  }
  return(list(mixwLB = mixwLB, mixwGB = mixwGB))
  
}
```

```{r}
moveOperation <- function(particle, mSIBSSD.list, w.ratio = w.ratio, mixwLB, mixwGB, qLB, qGB){
  for(i in 1:particle){
    
    if(mixwGB[[i]]$value > mixwLB[[i]]$value && mixwGB[[i]]$value > evaluateMBayesianD(MSSD = mSIBSSD.list[[i]], n1 = n1,n2 = n2)){
      mSIBSSD.list[[i]] <- mixwGB[[i]]$design 
      
    }else if(mixwLB[[i]]$value > mixwGB[[i]]$value && mixwLB[[i]]$value > evaluateMBayesianD(MSSD = mSIBSSD.list[[i]], n1 = n1,n2 = n2)){
      mSIBSSD.list[[i]] <- mixwLB[[i]]$design  
      
    }else{
      #radom
      w.qLB <- rbinom(n = 1, size = qLB, prob = w.ratio)
      s.qLB <- qLB - w.qLB
      w.replace.index <- sample(m1,w.qLB)
      s.replace.index <- sample(m2,s.qLB)
      replace.matrix <- generateMSSD(m1 = m1, m2 = m2, n1 = n1, n2 = n2)
      
      #wholeplot
      if(w.qLB != 0){
        
        mSIBSSD.list[[i]][,w.replace.index] <- replace.matrix[,w.replace.index]  
      }
       
      #subplot
      if(s.qLB != 0){
        mSIBSSD.list[[i]][,m1+s.replace.index] <- replace.matrix[,m1+s.replace.index]  
      }
      
    }
  }
  return(mSIBSSD.list)
}
```