---
title: "spilt-plot_MSIBSSD_BayesianD"
output: html_document
---
Denote m1 the number
of whole-plot factors, m2 the number of subplot factors, n1 the number of whole plots, n2
the number of subplots within each whole plot.
```{r}
f = 2
m1 = 8
m2 = 8
n1 = 6
n2 = 6
MSSD <- as.matrix(read.csv("D:/statisic/Master_thesis/spilt-plot_MSIBSSD_BayesianD/table1.csv",header = F))
print(MSSD)
```

```{r}
source_rmd <- function(file, local = FALSE, ...){
  options(knitr.duplicate.label = 'allow')

  tempR <- tempfile(tmpdir = ".", fileext = ".R")
  on.exit(unlink(tempR))
  knitr::purl(file, output=tempR, quiet = TRUE)

  envir <- globalenv()
  source(tempR, local = envir, ...)
}
Sys.setlocale('LC_ALL','C')
source_rmd("D:/statisic/Master_thesis/spilt-plot_MSIBSSD_BayesianD/spilt-plot_MSIBSSD_BayesianD_functions.Rmd")
```
```{r}
evaluateMBayesianD(MSSD = MSSD, n1 = n1, n2 = n2)
```

```{r}
Dcriterion <- function(mSSD, f = f,m1 = m1, m2 = m2, n1 = n1,n2 = n2){
  index.matrix <- combn(ncol(mSSD), f)
  library(Matrix)   
  Z <- kronecker(diag(n1),matrix(1,n2,1))
  S <- diag(n1 * n2) + (1 * Z %*% t(Z))
  
  Df <- 0
  for(i in 1:ncol(index.matrix)){
    Xf <- cbind(1, mSSD[ ,index.matrix[,i]])
    Df <- Df + det(t(Xf) %*% solve(S) %*% Xf)^(1/(f+1))
  }
  return(Df / choose(ncol(mSSD), f))
}
Dcriterion(mSSD = MSSD,f = f,m1 = m1, m2 = m2, n1 = n1,n2 = n2)
```

# main function
```{r}
spilt_plot_MSIBSSD_BayesianD <- function(particle, m1, m2, n1, n2, qLB, qGB, w.ratio, iteration, early.break = 100){
  
  #1: Randomly generate a set of balanced N*m SSDs as initial particles
  mSIBSSD.list <- list()
  for(i in 1:particle){
    mSIBSSD.list[[i]] <- generateMSSD(m1 = m1, m2 = m2, n1 = n1, n2 = n2)  
  }
  
  #2: Evaluate objective function value of each SSD
  BayesianD.value <- numeric(particle)
  for(j in 1:particle){
    BayesianD.value[j] <- evaluateMBayesianD(MSSD = mSIBSSD.list[[j]],n1 = n1,n2 = n2)  
  }
  
  #3: Initialize the LB for all SSDs
  LB <- list()
  for(i in 1:particle){
    LB[[i]] <- list(design = mSIBSSD.list[[i]], value = BayesianD.value[i])   
  }
  
  #4: Initialize the GB
  GB <- LB[[1]]
  for(i in 1:particle){
    if(LB[[i]]$value > GB$value)
    GB <- LB[[i]]   
  }
  
  #record the GB value
  record <- GB$value
  
  #5: while not converge do
  progress <- 0                            #index for print when make progress and early break
  break.index <- 1
  for(i in 1:iteration){
    
    #deal with early break and print when make progress
    if((i - break.index) >= early.break){
      break  
    }else if(progress == 1){
      print(GB)
      progress <- 0
      break.index <- i
    }

    
    
    #6: For each SSD, perform the MIX operation 
    mixw <- mixOperation(particle = particle,mSIBSSD.list = mSIBSSD.list, w.ratio = w.ratio, LB = LB,GB = GB, qLB = qLB, qGB = qGB)
    
   
    #7: For each SSD, perform the MOVE operation
    mSIBSSD.list <- moveOperation(particle = particle,
                                  mSIBSSD.list = mSIBSSD.list,
                                  w.ratio = w.ratio,
                                  mixwLB = mixw$mixwLB, 
                                  mixwGB = mixw$mixwGB, 
                                  qLB = qLB, 
                                  qGB = qGB)
    
    #9: Update the LB for all SSDs
    BayesianD.value <- numeric(particle)
    for(j in 1:particle){
      BayesianD.value[j] <- evaluateMBayesianD(MSSD = mSIBSSD.list[[j]], n1 = n1,n2 = n2)  
    }

    for(j in 1:particle){
      if(BayesianD.value[j] > LB[[j]]$value){
        LB[[j]] <- list(design = mSIBSSD.list[[j]], value = BayesianD.value[j])  
      }
    }
    
    #10: Update the GB
    if(max(BayesianD.value) > GB$value){
      GB <- LB[[which.max(BayesianD.value)]] 
      progress <- 1
    }
  
  record <- c(record,GB$value)

  #11: end while
  }
  return(list(GB,record))  
}
```

###start###
#test
```{r}
library(tictoc)
tic()
m1 = 8
m2 = 8
n1 = 6
n2 = 6
qLB = 4
qGB = 3
w.ratio = 0.2
spilt_plot_MSIBSSD_BayesianD(particle = 10, m1 = m1, m2 = m2, n1 = n1, n2 = n2, qLB = qLB, qGB = qGB,w.ratio = w.ratio, iteration = 10,early.break = 100)
toc()
```

#500 particles, iteraion 500 times
```{r}
library(tictoc)
tic()
m1 = 8
m2 = 8
n1 = 6
n2 = 6
qLB = 4
qGB = 3
w.ratio = 0.2
result <- spilt_plot_MSIBSSD_BayesianD(particle = 500, m1 = m1, m2 = m2, n1 = n1, n2 = n2, qLB = qLB, qGB = qGB,w.ratio = w.ratio, iteration = 500,early.break = 100)
toc()
```

```{r}
result
Dcriterion(mSSD = result[[1]]$design,f = 2,m1 = m1, m2 = m2, n1 = n1,n2 = n2)
```


